[phases.setup]
nixPkgs = ["...", "nodejs_20", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd frontend && npm ci --include=dev"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python start.py"
